### ISSUE TITLE
Retired characters might leave corrupt grid

### ISSUE THREAD

**Issue by ghost** [mangband/mangband#1009]
Issue raised by flambard

In kingly() (the function that handles retirement to a warm, sunny climate), dungeon depth is set to 0, the grid is cleared after that, and it's obviously the wrong location (unless, player does retire at depth 0). Thus, the actual spot becomes unusable.

Reported by Thorbear.

Probably related to/reason of the server crash that happens after a bellow-level-40 character retires.

**Comment by flambard-took** [comment]
Historical note by PowerWyrm:

>Since I still don't have my password back and I can't post comments on trac, I'll put them here:
- setting p_ptr->depth = 0 in kingly() makes Delete_player fail in a really nasty way, since the player is not really in town; this should be removed at once (I checked TomeNET's code, and this has been removed ages ago in that code)
- the p_ptr->depth = 0 line comes from Vanilla code, in which retiring is final since there's only one player, so it doesn't matter; the code exists since frog-knows (the first version)
