### ISSUE TITLE
Farmers can't choose their crop.

### ISSUE THREAD

**Issue by billsey** [mangband/mangband#1024]
When someone 'farms' a field by harvesting what is there, they should be able to then choose what the next crop will be by 'seeding' the field. I suggest that a player could throw the appropriate type of grown food item onto an empty field, which would then, over time, grow that type of food. Potential drawbacks would be that every field would eventually grow mushrooms. Foods that aren't viable as crops would include standard food rations, dried jerky, fine wine and the like (why don't we grow grapes, to make the wine?).

**Comment by flambard-took** [comment]
Since the wilderness levels are deallocated all the time, all the changes made to the terrain are constantly lost. Meaning, this whole feature makes VERY LITTLE SENSE, as the crop types will reset to random every time. However, there is a way for a player to work around this: a) he can stay on the level ("doing some farm-work"?) b) he can buy (or build!) a house on the level, making it "perma-static" (thanks to a hack we have). THEN, if there's a field nearby his house, he can start his farm!

**Comment by draconisPW** [comment]
You can't currently "plant" potatoes because WILD_CROP_POTATO = 0 and in do_cmd_plant_seed() if crop is zero the function returns immediately.

**Comment by flambard-took** [comment]
thanks, how did you fix it?

**Comment by flambard-took** [comment]
ah, I see, no need to adjust WILD_CROP_POTATO or anything, it's a bug in the function.
