### ISSUE TITLE
Recharging isn't right

### ISSUE THREAD

**Issue by grking** [mangband/mangband#1188]
Now we stack wands and staves, it's been reported the recharge spell isn't too great when working on a stack.

I tried vanilla (4.1.3), and it seems fine.  Even with the lesser recharge spell I can recharge a stack multiple times, and it simply adds 3 or 4 charges to the stack each time.

When it fails however, it removes (destroys) one of the items in the stack.

This kind of makes sense, as it does seem wands and staves are a bit over powered right now.  A large stack becomes effectively infinite charges, with no risk.

Investigate in detail how vanilla recharging works, for spells and scrolls and implement it here.

**Comment by flambard-took** [comment]
Angband < 3.0.6 -- staves/wands destroyed on backfire. (MAngband 0.7.2=same)
Angband >= 3.0.6 < 3.0.9 -- staves/wands drain all charges in stack on backfire. (MAngband 1.1.X=same)
Angband 3.0.9 -- saves/wands destroyed on backfire once again. Also, new backfire formula. (we're now here)
Angband 3.X.X - 3.5.1 (not sure which version introduced this) -- backfiring no longer removes item knowledge.
Angband 4.1.3 -- same as before (but the code looks a bit different)

As per #876, we're now fully synced with Angband 3.0.9.
If you also want "don't mangle item knowledge" behavior from latest Angband, simply delete this code:
```
/* *Identified* items keep the knowledge about the charges */
if (!(o_ptr->ident & ID_MENTAL))
{
    /* We no longer "know" the item */
    o_ptr->ident &= ~(ID_KNOWN);
}
```

**Comment by flambard-took** [comment]
Turns out, the item knowledge deal is pretty simple:

Angband 3.0.6 introduced "safe recharge", which replaced wand/staff destruction on backfire with *another* penalty: all charges are drained and you forget your item ID.

When Angband 3.0.9 reverted this and re-introduced wand/staff destruction, they simply forgot to revert that bit of code. Soon after, in Angband 3.1.0beta, this was amended.

So there's really no question about it, those are 2 distinct behaviors, you either get destruction, either ID loss and charge drain.

**Comment by flambard-took** [comment]
Closing as duplicated of #876.
