### ISSUE TITLE
Restore 'bump_open' option from MAngband 0.7

### ISSUE THREAD

**Issue by igroglaz** [mangband/mangband#1328]
easy_alter option open/disable doors/traps on movement.

It would be fun to have two separate options, eg I like to open doors by movement, but I like to disarm traps manually (D)

**Comment by flambard-took** [comment]
Agreed, I'd like to separate those options too. Plus, `bump_open` was a classic option, introduced by APD, and I still remember being excited about it :)

Note, in V, there's an `easy_open` option, but we shouldn't use that name, because it does something different: it bypasses a direction prompt completely.
