### ISSUE TITLE
Floor items stacking

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#597]
Issue raised by flambard

It was speculated for a long time, that items falling on the floor shall stack, mainly to assist rangers with their projectiles and to help save some items on monster/player death (It is also like that in angband 3.0.6).

**Comment by flambard-took** [comment]
The items stacking on the floor are not merged properly.

We just do j_ptr->number += o_ptr->number, and that's it! :( Instead, `object_absorb(j_ptr, o_ptr)` should be called, so inscriptions, discounts and wand/staff/rod charges are properly carried over.

In addition, `object_similar_floor` only handles ammo (as per the OP) and potions/scroll/food, but there's little reason for it to ignore other items.

This can lead to unfair situations when players loose items that *should* stack, *do* stack in inventory, but not on the floor. For example, [here, karis](https://mangband.org/forum/viewtopic.php?f=19&t=1695#p7467) tells a sad story:
>  tried to drop mage books in a full house on top of other mage books. The dropped mage books vanished.
I made sure to stay on the top of the right book pile (i.e. Resistances), when dropping another book of the same type on the pile. And the inscription was definitly the same. And I was able to reproduce it.
Otherwise i do the same things with *healing* pots and staffs, this works.
