### ISSUE TITLE
Spacetime Bubbles and Bullet Time

### ISSUE THREAD

**Issue by mangband** [mangband/mangband#689]
Issue raised by jug

A big complaint (perhaps the biggest) about MAngband is that it becomes more a frantic game of reflexes rather than a considered strategic and tactical affair like Angband.  There are few players who haven't died at least once because they couldn't hit the right key fast enough. More likely almost every death is like this.

There is a solution.  Think "Bullet Time".

Time is relative.  Unlike physical reality however time in MAngband is relative to the dungeon depth not the observer.  Currently time slows down the deeper you get in the dungeon.  But if time _were_ relative to the observer (i.e. the character) then time could be manipulated in several interesting ways.

One way we could manipulate time is to slow time down as character hitpoints become lower.  So as the Tarrasque blows 90% of your hitpoints away in one round time suddenly slows down, the player has time to think his next move, remember which key is his tele macro and act properly.

Another interesting way we could manipulate time is to speed up time, so running and resting become more like Angband, very very fast.

**Comment by draconisPW** [comment]
There are still two problems with classic MAngband system:
1) No running in sight of unmovable harmless mob (mushroom, mold, ...) -- it's a huge annoyance when you enter a long lit area with some unmovable mob that cannot ever harm you and forces you to move step by step (especially early on when you have zero base speed) when you could simply run past it or come close and shoot it, trickier to handle since there are actually unmovable mobs that are a real threat (drujs for example), so maybe add an option to allow running when in LoS of unmovable mobs (like it's done for sleeping mobs)
2) Cheezy advantage for the player who can simply move past a corner and run while mobs are still stuck walking -- mobs should be able to speed up when NOT in LoS of the player so they're not left behind when they wake up out of LoS (except in town)

**Comment by draconisPW** [comment]
Also non hostile monsters shouldn't impede running. This should be the case for DM with DM_MONSTER_FRIEND flag set.
